### PR TITLE
fix: data browser does not allow meta to be edited for paths without any meta

### LINKED ISSUE #1744: Can't add new meta data
If a path has no meta data at all, then it does not show in the data browser, so meta can't be added.

### PR DESCRIPTION
**Pull request by sbender9**
Fixes #1744

### CODE REVIEW

File: packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js [hunk 1]
```diff
@@ -396,23 +396,27 @@ class DataBrowser extends Component {
...
                           )
                         })
                         .sort()
                         .map((key) => {
-                          const meta = this.state.meta[this.state.context][key]
-                          const path = key
+                          const data = this.state.data[this.state.context][key]
+                          const meta =
+                            this.state.meta[this.state.context][data.path]
+                          const path = data.path
```
Comment (tkurki) [inline packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js]: Why do we need to get data by key that is path and then get the path from the data, instead of `path = key`? Or to make it simpler rename the map handler parameter `path`?

Comment (sbender9) [reply packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js]: key != path. key is "path + $source"

Comment (sbender9) [reply packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js]: But there is a problem. The path will show in the list multiple times if there are multiple sources. I'll fix that...
