### PR TITLE
fix(security): include timeToLive in login responses

### LINKED ISSUE #1476: doc: Security implementation discrepancies
There are two issues I found. See [Specification - Security](https://signalk.org/specification/1.7.0/doc/security.html#authentication-via-http)

1. The authentication via HTTP security doc states: 

> In response to a valid login, the server shall respond with a 200 (OK) status, set an HTTP session cookie and include the token expiry in seconds and the token value in the body of the response. The response Content-Type must be application/json.

The REST response body is defined as:
```
{
  "timeToLive": 86400,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2UiOiIxMjM0LTQ1NjUz"
}
```

**REST login discrepancy:** When using login REST call, the POST response has the token in both the Set-Cookie header and in the cookie, but not the response body (as stated above).

2. The WebSocket login sequence documentation states:

> If the login is successful, the server will send a response like the following:

```
{
  "requestId": "1234-45653-343454",
  "state": "COMPLETED",
  "result": 200,
  "login": {
  	"timeToLive": 86400,
    "token": "eyJhbGciOiJIUzI1NiIsI...ibtv41fOnJObT4RdOyZ_UI9is8"
  }
}
```

**WebSocket response discrepancy:** Note that I am not sure if its a code or doc issue but, the `timeToLive` key is missing in the response. This make the section about Token Validation - Other Clients (see [Other Clients](https://signalk.org/specification/1.7.0/doc/security.html#other-clients-1)) not plainly
usable, unless you extract the TTL from the token.

Also of note, the [Access Request doc](https://signalk.org/specification/1.7.0/doc/access_requests.html#access-requests) is in the Appendix E. I had to ask around for someone to tell me it existed. I was think that since it was not part of the Security section, that it was missing from the doc. Should it not be together? Just an opinion from someone working on implementing user and device security API calls...

Thanks

### PR DESCRIPTION
**Pull request by dirkwa**
Fixes #1476

### Summary 

The Signal K specification requires login responses to include a `timeToLive` field indicating how long the token is valid, in seconds. The server was only returning the `token` field.

Adds `timeToLive` to both REST (`/signalk/v1/auth/login`) and WebSocket login responses. When the server's token expiration is set to `NEVER`, the field is omitted.

### Test

Tested manually against a server with security enabled (port 4000):

**REST login:**

```
curl -s -X POST http://localhost:4000/signalk/v1/auth/login \
  -H 'Content-Type: application/json' \
  -d '{"username":"admin","password":"***"}' | jq
```

Response includes `timeToLive` (in seconds) alongside `token`.

**WebSocket login:**

```
wscat -c ws://localhost:4000/signalk/v1/stream
> {"requestId":"1","login":{"username":"admin","password":"***"}}
```

Response includes `timeToLive` in the login reply.

**NEVER expiration:** With server configured for `NEVER` token expiration, verified `timeToLive` is correctly omitted from the response.

**Duration calculations verified:** `1h`→3600, `24h`→86400, `7d`→604800.

## Summary by CodeRabbit

* **New Features**
  * Login responses now include token expiration time, enabling applications to inform users about session duration.

### CODE REVIEW

File: src/tokensecurity.ts [hunk 1]
```diff
@@ -778,7 +782,16 @@ function tokenSecurityFactory(
                 configuration.secretKey,
                 jwtOptions
               )
-              resolve({ statusCode: 200, token, user: user.username })
+              const timeToLive =
+                theExpiration !== 'NEVER'
+                  ? Math.floor(ms(theExpiration as StringValue) / 1000)
+                  : undefined
```
Comment (tkurki) [inline src/tokensecurity.ts]: I think `null` would be more appropriate here, indicating the explicit absence of value. A missing property does not really tell you much.

```suggestion
                  : null
```

**Comment by dirkwa** [comment]
@coderabbitai full review

**Comment by dirkwa** [comment]
ready for human review
