### PR TITLE
fix: reject deltas with invalid values entries

### LINKED ISSUE #1473: Block deltas with null or missing path
Plugins consuming deltas may not implement error handling properly or just deliberately choose to log deltas / pathvalues with missing paths, causing support requests and annoyance.

I think it would be a good idea to discard them outright or have a configurable option to do so. Along with enough but not continuous logging to find the culprit.

### LINKED ISSUE #1708: Tokensecurity error on reading properties
On my windows 10 install SignalK v.2.6.2 I get the following error in the log:
```
TypeError: Cannot read properties of null (reading 'path') at c:\signalk\nodejs\node_modules\signalk-server\lib\tokensecurity.js:468:98 
at Array.find (<anonymous>) at c:\signalk\nodejs\node_modules\signalk-server\lib\tokensecurity.js:467:35 
at Array.find (<anonymous>) at strategy.shouldAllowWrite (c:\signalk\nodejs\node_modules\signalk-server\lib\tokensecurity.js:461:46) 
at processUpdates (c:\signalk\nodejs\node_modules\signalk-server\lib\interfaces\ws.js:366:31)
```

I've dropped all devices in 'Security', but that doesn't help. Reinstalled signalK: no dice.

### PR DESCRIPTION
**Pull request by dirkwa**
Fixes #1708
Fixes #1473

### Summary

Malformed deltas with null entries or pathvalues with missing/null `path` in the `values` array crash `shouldAllowWrite()` with "Cannot read properties of null". The entire delta is rejected as invalid rather than filtering individual bad values, keeping per-delta processing overhead minimal.

Validation covers all entry points:

- `handleMessage` in `index.ts` — rejects before any processing (source assignment, timestamps, delta chain), covers WS, plugins, and providers
- `shouldAllowWrite` in `tokensecurity.ts` — prevents crash in the WS security check that runs before `handleMessage`

### Tested manually against server by sending deltas over WebSocket:

- `null` entry in values array → entire delta rejected, warning logged
- Pathvalue with missing `path` (`{value: 3.14}`) → rejected
- Pathvalue with `path: null` → rejected
- Valid delta → processed normally, value stored in data model

Server console output confirmed three rejection warnings followed by successful GET of the valid value.

## Summary by CodeRabbit

* **Bug Fixes**
  * Malformed update entries are now rejected early during processing, preventing invalid or incomplete payloads from being processed.
  * Write attempts containing malformed value or metadata path entries are now denied, strengthening access control and preventing unauthorized or malformed writes.
  * A warning is logged when malformed updates are detected (includes source identifier) to aid troubleshooting.

### CODE REVIEW

**Comment by tkurki** [comment]
This does not fix #1473 as is ws specific.

Would a better fix be to make security deny malformed deltas? 

I am not terribly crazy about adding the filter step to each and every delta. we could just ignore the whole delta as invalid if there is bad data. Processing overhead would be a bit less. It would affect only a very miniscule portion of data, as the vast majority is good.

**Comment by dirkwa** [comment]
Thanks for the quick feedback. All topics addressed.

File: src/tokensecurity.ts [hunk 1]
```diff
@@ -1138,6 +1138,13 @@ function tokenSecurityFactory(
         }
 
         if (hasValues(update)) {
+          if (
+            update.values.some(
```
Comment (tkurki) [inline src/tokensecurity.ts]: Let’s iterate over values once, not twice in a row. See below.

**Comment by dirkwa** [comment]
@coderabbitai full review

**Comment by dirkwa** [comment]
@coderabbitai full review

**Comment by dirkwa** [comment]
ready for human review

**Comment by dirkwa** [comment]
@coderabbitai

I think you are blaming false positive:

Finding 1 (dead code claim):

The earlier validation (lines 315-334) only checks values, not meta — so the meta branch at line 359 is not redundant. And even for values, the earlier check discards the entire delta when any update has invalid values, while the per-update check at line 354 is a finer-grained cleanup within the .map() that strips a bad values field from one update while letting the rest of the delta's valid updates proceed. These are two different levels of defense — the per-update checks are not dead code.

Finding 2 (meta guard):

Already fixed in this commit — same null/undefined/non-string guard pattern as the values branch.

**Comment by dirkwa** [comment]
ready for human review

**Comment by dirkwa** [comment]
@coderabbitai resume

**Comment by tkurki** [comment]
Sorry about going a bit back and forth with this, but i realised we already iterate and filter updates, so the additional check fits there very well. What do you think?

**Comment by msallin** [comment]
@dirkwa pinging you since Im currently looking at PRs and noticed that you might missed Teppos question.

**Comment by dirkwa** [comment]
Thanks for the follow-up, and for pushing the refactor commit directly — that's exactly the right structure. The validation now lives inside the existing `.map()` filter in `handleMessage`, extracted as a named `isValidUpdate` type guard. Invalid updates are filtered out individually rather than discarding the whole delta, so valid updates from the same message still get processed.

The `shouldAllowWrite` check in `tokensecurity.ts` is also a single-pass iteration now — the null/missing-path check is part of the same `find()` loop that does the ACL check, so each value is only visited once.

CI is green. I think this is ready for another look.
